# Generated by Django 5.0.6 on 2026-07-13 11:39

import django.db.models.deletion
import journal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.PositiveIntegerField()),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-volume__year', '-volume__number', '-issue_number'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('issn', models.CharField(blank=True, max_length=20, verbose_name='ISSN')),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', validators=[journal.models.validate_cover_image])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, help_text='Assigned Editor responsible for this journal', limit_choices_to={'profile__role': 'editor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals_edited', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(help_text='Comma-separated keywords', max_length=300)),
                ('subject_area', models.CharField(max_length=150)),
                ('co_authors', models.CharField(blank=True, help_text='Comma-separated names of co-authors (if any)', max_length=500)),
                ('manuscript_file', models.FileField(upload_to='manuscripts/', validators=[journal.models.validate_manuscript_file])),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Screening'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('published', 'Published')], default='submitted', max_length=20)),
                ('editor_decision_comment', models.TextField(blank=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corresponding_author', models.ForeignKey(limit_choices_to={'profile__role': 'author'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(blank=True, help_text='Assigned once the article is scheduled for publication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='journal.issue')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='journal.journal')),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Volume Number')),
                ('year', models.PositiveIntegerField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='journal.journal')),
            ],
            options={
                'ordering': ['-year', '-number'],
                'unique_together': {('journal', 'number')},
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='journal.volume'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Invitation'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('recommendation', models.CharField(blank=True, choices=[('accept', 'Accept'), ('minor_revision', 'Minor Revision'), ('major_revision', 'Major Revision'), ('reject', 'Reject')], max_length=20)),
                ('comments_to_author', models.TextField(blank=True)),
                ('confidential_comments', models.TextField(blank=True, help_text='Visible to Editors only')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(limit_choices_to={'profile__role': 'reviewer'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='journal.submission')),
            ],
            options={
                'ordering': ['-invited_at'],
                'unique_together': {('submission', 'reviewer')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('volume', 'issue_number')},
        ),
    ]
