# Generated by Django 5.2.16 on 2026-07-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Journal Category',
                'verbose_name_plural': 'Journal Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='journal',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='journals', to='journal.journalcategory'),
        ),
    ]
